apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: span_id
          matcherRegex: '"span_id":"([a-f0-9]+)"'
          url: '{span:id="$${__value.raw}"}'
          datasourceUid: Tempo

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        customQuery: true
        datasourceUid: Loki
        query: '{service_name="$${__span.tags["service.name"]}"} |= `$${__span.spanId}`'
        tags:
          - key: service.name
            value: service_name