/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/bson"

	"github.com/free5gc/udr/internal/logger"
	"github.com/free5gc/util/metrics/sbi"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
)

func (p *Processor) QueryAmDataProcedure(c *gin.Context, collName string, ueId string, servingPlmnId string) {
	logger.DataRepoLog.Infof("QueryAmDataProcedure: ueId: %s, servingPlmnId: %s", ueId, servingPlmnId)

	ctx, span := otel.Tracer("udr-processor").Start(
		c.Request.Context(),
		"UDR QueryAmData",
	)
	span.SetAttributes(
		attribute.String("ue.id", ueId),
		attribute.String("serving_plmn", servingPlmnId),
		attribute.String("udr.collection", "AccessAndMobilitySubscriptionData"),
	)
	defer span.End()

	c.Request = c.Request.WithContext(ctx)

	filter := bson.M{"ueId": ueId, "servingPlmnId": servingPlmnId}
	data, pd := p.GetDataFromDB(collName, filter)
	if pd != nil {
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, pd.Cause)
		c.JSON(int(pd.Status), pd)
		return
	}

	c.JSON(http.StatusOK, data)
}
